FROM golang:1.22.1 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main ./cmd/main.go


FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/main .

CMD ["./main"]
